# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NemPyTracker.ui'
#
# Created: Wed Jul 16 15:03:12 2014
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TrackerUI(object):
    def setupUi(self, TrackerUI):
        TrackerUI.setObjectName("TrackerUI")
        TrackerUI.resize(2000, 1200)
        TrackerUI.setMinimumSize(QtCore.QSize(1400, 1200))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        TrackerUI.setFont(font)
        self.centralwidget = QtWidgets.QWidget(TrackerUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 411, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1340, 120, 593, 986))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonConnect = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonConnect.setObjectName("buttonConnect")
        self.gridLayout.addWidget(self.buttonConnect, 10, 0, 1, 1)
        self.buttonStartRecording = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonStartRecording.setFont(font)
        self.buttonStartRecording.setObjectName("buttonStartRecording")
        self.gridLayout.addWidget(self.buttonStartRecording, 23, 1, 1, 1)
        self.fps = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fps.setFont(font)
        self.fps.setObjectName("fps")
        self.gridLayout.addWidget(self.fps, 24, 1, 1, 2)
        self.scaling = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scaling.setFont(font)
        self.scaling.setObjectName("scaling")
        self.gridLayout.addWidget(self.scaling, 13, 0, 1, 3)
        self.sourceCombo = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sourceCombo.setFont(font)
        self.sourceCombo.setObjectName("sourceCombo")
        self.gridLayout.addWidget(self.sourceCombo, 6, 1, 1, 2)
        self.recordingDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.recordingDesc.setFont(font)
        self.recordingDesc.setObjectName("recordingDesc")
        self.gridLayout.addWidget(self.recordingDesc, 23, 0, 1, 1)
        self.buttonMotorsOff = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonMotorsOff.setFont(font)
        self.buttonMotorsOff.setToolTip("")
        self.buttonMotorsOff.setObjectName("buttonMotorsOff")
        self.gridLayout.addWidget(self.buttonMotorsOff, 22, 2, 1, 1)
        self.fpsDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fpsDesc.setFont(font)
        self.fpsDesc.setObjectName("fpsDesc")
        self.gridLayout.addWidget(self.fpsDesc, 24, 0, 1, 1)
        self.studyName = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.studyName.setFont(font)
        self.studyName.setObjectName("studyName")
        self.gridLayout.addWidget(self.studyName, 3, 1, 1, 2)
        self.loggingCombo = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loggingCombo.setFont(font)
        self.loggingCombo.setObjectName("loggingCombo")
        self.gridLayout.addWidget(self.loggingCombo, 8, 1, 1, 2)
        self.methodCombo = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.methodCombo.setFont(font)
        self.methodCombo.setObjectName("methodCombo")
        self.gridLayout.addWidget(self.methodCombo, 7, 1, 1, 2)
        self.pushReset = QtWidgets.QPushButton(self.layoutWidget)
        self.pushReset.setObjectName("pushReset")
        self.gridLayout.addWidget(self.pushReset, 10, 2, 1, 1)
        self.methodDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.methodDesc.setFont(font)
        self.methodDesc.setObjectName("methodDesc")
        self.gridLayout.addWidget(self.methodDesc, 7, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 12, 0, 1, 3)
        self.loggingDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loggingDesc.setFont(font)
        self.loggingDesc.setObjectName("loggingDesc")
        self.gridLayout.addWidget(self.loggingDesc, 8, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 18, 0, 1, 3)
        self.scalingSlider = QtWidgets.QSlider(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scalingSlider.setFont(font)
        self.scalingSlider.setMinimum(1)
        self.scalingSlider.setMaximum(30)
        self.scalingSlider.setOrientation(QtCore.Qt.Horizontal)
        self.scalingSlider.setObjectName("scalingSlider")
        self.gridLayout.addWidget(self.scalingSlider, 14, 0, 1, 3)
        self.buttonDown = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonDown.setFont(font)
        self.buttonDown.setObjectName("buttonDown")
        self.gridLayout.addWidget(self.buttonDown, 17, 1, 1, 1)
        self.motorsDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.motorsDesc.setFont(font)
        self.motorsDesc.setObjectName("motorsDesc")
        self.gridLayout.addWidget(self.motorsDesc, 22, 0, 1, 1)
        self.buttonRight = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonRight.setFont(font)
        self.buttonRight.setObjectName("buttonRight")
        self.gridLayout.addWidget(self.buttonRight, 16, 2, 1, 1)
        self.buttonLeft = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonLeft.setFont(font)
        self.buttonLeft.setObjectName("buttonLeft")
        self.gridLayout.addWidget(self.buttonLeft, 16, 0, 1, 1)
        self.buttonUp = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonUp.setFont(font)
        self.buttonUp.setObjectName("buttonUp")
        self.gridLayout.addWidget(self.buttonUp, 15, 1, 1, 1)
        self.buttonStopRecording = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonStopRecording.setFont(font)
        self.buttonStopRecording.setObjectName("buttonStopRecording")
        self.gridLayout.addWidget(self.buttonStopRecording, 23, 2, 1, 1)
        self.buttonMotorsOn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonMotorsOn.setFont(font)
        self.buttonMotorsOn.setObjectName("buttonMotorsOn")
        self.gridLayout.addWidget(self.buttonMotorsOn, 22, 1, 1, 1)
        self.studyDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.studyDesc.setFont(font)
        self.studyDesc.setObjectName("studyDesc")
        self.gridLayout.addWidget(self.studyDesc, 3, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 5, 0, 1, 3)
        self.buttonRun = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonRun.setObjectName("buttonRun")
        self.gridLayout.addWidget(self.buttonRun, 10, 1, 1, 1)
        self.sourceDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sourceDesc.setFont(font)
        self.sourceDesc.setObjectName("sourceDesc")
        self.gridLayout.addWidget(self.sourceDesc, 6, 0, 1, 1)
        self.boundaryDesc = QtWidgets.QLabel(self.layoutWidget)
        self.boundaryDesc.setObjectName("boundaryDesc")
        self.gridLayout.addWidget(self.boundaryDesc, 9, 0, 1, 1)
        self.boundaryEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.boundaryEdit.setObjectName("boundaryEdit")
        self.gridLayout.addWidget(self.boundaryEdit, 9, 1, 1, 2)
        self.coloringDesc = QtWidgets.QLabel(self.layoutWidget)
        self.coloringDesc.setObjectName("coloringDesc")
        self.gridLayout.addWidget(self.coloringDesc, 11, 0, 1, 1)
        self.coloringCombo = QtWidgets.QComboBox(self.layoutWidget)
        self.coloringCombo.setObjectName("coloringCombo")
        self.gridLayout.addWidget(self.coloringCombo, 11, 1, 1, 2)
        self.videoFrame = QtWidgets.QLabel(self.centralwidget)
        self.videoFrame.setGeometry(QtCore.QRect(30, 90, 1280, 960))
        self.videoFrame.setObjectName("videoFrame")
        TrackerUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TrackerUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2000, 47))
        self.menubar.setObjectName("menubar")
        TrackerUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TrackerUI)
        self.statusbar.setObjectName("statusbar")
        TrackerUI.setStatusBar(self.statusbar)

        self.retranslateUi(TrackerUI)
        QtCore.QMetaObject.connectSlotsByName(TrackerUI)

    def retranslateUi(self, TrackerUI):
        _translate = QtCore.QCoreApplication.translate
        TrackerUI.setWindowTitle(_translate("TrackerUI", "NemPy Tracker"))
        self.label.setText(_translate("TrackerUI", "Video Display"))
        self.buttonConnect.setText(_translate("TrackerUI", "Connect"))
        self.buttonStartRecording.setText(_translate("TrackerUI", "Start"))
        self.fps.setText(_translate("TrackerUI", "TextLabel"))
        self.scaling.setText(_translate("TrackerUI", "TextLabel"))
        self.recordingDesc.setText(_translate("TrackerUI", "Recording"))
        self.buttonMotorsOff.setText(_translate("TrackerUI", "Off"))
        self.fpsDesc.setText(_translate("TrackerUI", "FPS"))
        self.pushReset.setText(_translate("TrackerUI", "Reset"))
        self.methodDesc.setText(_translate("TrackerUI", "Method"))
        self.loggingDesc.setText(_translate("TrackerUI", "Logging"))
        self.buttonDown.setText(_translate("TrackerUI", "Down"))
        self.motorsDesc.setText(_translate("TrackerUI", "Motorized"))
        self.buttonRight.setText(_translate("TrackerUI", "Right"))
        self.buttonLeft.setText(_translate("TrackerUI", "Left"))
        self.buttonUp.setText(_translate("TrackerUI", "Up"))
        self.buttonStopRecording.setText(_translate("TrackerUI", "Stop"))
        self.buttonMotorsOn.setText(_translate("TrackerUI", "On"))
        self.studyDesc.setText(_translate("TrackerUI", "Study"))
        self.buttonRun.setText(_translate("TrackerUI", "Run"))
        self.sourceDesc.setText(_translate("TrackerUI", "Source"))
        self.boundaryDesc.setText(_translate("TrackerUI", "Boundary"))
        self.coloringDesc.setText(_translate("TrackerUI", "Coloring"))
        self.videoFrame.setText(_translate("TrackerUI", "TextLabel"))

