# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NemPyTracker.ui'
#
# Created: Tue Jul 22 12:30:45 2014
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TrackerUI(object):
    def setupUi(self, TrackerUI):
        TrackerUI.setObjectName("TrackerUI")
        TrackerUI.resize(2000, 1200)
        TrackerUI.setMinimumSize(QtCore.QSize(1400, 1200))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        TrackerUI.setFont(font)
        self.centralwidget = QtWidgets.QWidget(TrackerUI)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1330, 10, 593, 1094))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.coloringDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.coloringDesc.setFont(font)
        self.coloringDesc.setObjectName("coloringDesc")
        self.gridLayout.addWidget(self.coloringDesc, 11, 0, 1, 1)
        self.methodCombo = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.methodCombo.setFont(font)
        self.methodCombo.setObjectName("methodCombo")
        self.gridLayout.addWidget(self.methodCombo, 8, 1, 1, 2)
        self.methodDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.methodDesc.setFont(font)
        self.methodDesc.setObjectName("methodDesc")
        self.gridLayout.addWidget(self.methodDesc, 8, 0, 1, 1)
        self.buttonRefresh = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonRefresh.setObjectName("buttonRefresh")
        self.gridLayout.addWidget(self.buttonRefresh, 13, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 15, 0, 1, 3)
        self.scalingSlider = QtWidgets.QSlider(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scalingSlider.setFont(font)
        self.scalingSlider.setMinimum(1)
        self.scalingSlider.setMaximum(30)
        self.scalingSlider.setOrientation(QtCore.Qt.Horizontal)
        self.scalingSlider.setObjectName("scalingSlider")
        self.gridLayout.addWidget(self.scalingSlider, 17, 0, 1, 3)
        self.loggingDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.loggingDesc.setFont(font)
        self.loggingDesc.setObjectName("loggingDesc")
        self.gridLayout.addWidget(self.loggingDesc, 9, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 21, 0, 1, 3)
        self.buttonDown = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonDown.setFont(font)
        self.buttonDown.setObjectName("buttonDown")
        self.gridLayout.addWidget(self.buttonDown, 20, 1, 1, 1)
        self.motorsDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.motorsDesc.setFont(font)
        self.motorsDesc.setObjectName("motorsDesc")
        self.gridLayout.addWidget(self.motorsDesc, 25, 0, 1, 1)
        self.buttonMotorsOn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonMotorsOn.setFont(font)
        self.buttonMotorsOn.setObjectName("buttonMotorsOn")
        self.gridLayout.addWidget(self.buttonMotorsOn, 25, 1, 1, 1)
        self.buttonStopRecording = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonStopRecording.setFont(font)
        self.buttonStopRecording.setObjectName("buttonStopRecording")
        self.gridLayout.addWidget(self.buttonStopRecording, 26, 2, 1, 1)
        self.buttonRight = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonRight.setFont(font)
        self.buttonRight.setObjectName("buttonRight")
        self.gridLayout.addWidget(self.buttonRight, 19, 2, 1, 1)
        self.buttonLeft = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonLeft.setFont(font)
        self.buttonLeft.setObjectName("buttonLeft")
        self.gridLayout.addWidget(self.buttonLeft, 19, 0, 1, 1)
        self.buttonUp = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonUp.setFont(font)
        self.buttonUp.setObjectName("buttonUp")
        self.gridLayout.addWidget(self.buttonUp, 18, 1, 1, 1)
        self.studyDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.studyDesc.setFont(font)
        self.studyDesc.setObjectName("studyDesc")
        self.gridLayout.addWidget(self.studyDesc, 3, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 5, 0, 1, 3)
        self.buttonRun = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonRun.setObjectName("buttonRun")
        self.gridLayout.addWidget(self.buttonRun, 13, 1, 1, 1)
        self.sourceDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sourceDesc.setFont(font)
        self.sourceDesc.setObjectName("sourceDesc")
        self.gridLayout.addWidget(self.sourceDesc, 6, 0, 1, 1)
        self.boundaryDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.boundaryDesc.setFont(font)
        self.boundaryDesc.setObjectName("boundaryDesc")
        self.gridLayout.addWidget(self.boundaryDesc, 10, 0, 1, 1)
        self.boundaryEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.boundaryEdit.setObjectName("boundaryEdit")
        self.gridLayout.addWidget(self.boundaryEdit, 10, 1, 1, 2)
        self.buttonConnect = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonConnect.setObjectName("buttonConnect")
        self.gridLayout.addWidget(self.buttonConnect, 13, 0, 1, 1)
        self.buttonStartRecording = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonStartRecording.setFont(font)
        self.buttonStartRecording.setObjectName("buttonStartRecording")
        self.gridLayout.addWidget(self.buttonStartRecording, 26, 1, 1, 1)
        self.sourceCombo = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sourceCombo.setFont(font)
        self.sourceCombo.setObjectName("sourceCombo")
        self.gridLayout.addWidget(self.sourceCombo, 6, 1, 1, 2)
        self.fps = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fps.setFont(font)
        self.fps.setObjectName("fps")
        self.gridLayout.addWidget(self.fps, 27, 1, 1, 2)
        self.scaling = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scaling.setFont(font)
        self.scaling.setObjectName("scaling")
        self.gridLayout.addWidget(self.scaling, 16, 0, 1, 3)
        self.fpsDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fpsDesc.setFont(font)
        self.fpsDesc.setObjectName("fpsDesc")
        self.gridLayout.addWidget(self.fpsDesc, 27, 0, 1, 1)
        self.loggingCombo = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loggingCombo.setFont(font)
        self.loggingCombo.setObjectName("loggingCombo")
        self.gridLayout.addWidget(self.loggingCombo, 9, 1, 1, 2)
        self.recordingDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.recordingDesc.setFont(font)
        self.recordingDesc.setObjectName("recordingDesc")
        self.gridLayout.addWidget(self.recordingDesc, 26, 0, 1, 1)
        self.studyName = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.studyName.setFont(font)
        self.studyName.setObjectName("studyName")
        self.gridLayout.addWidget(self.studyName, 3, 1, 1, 2)
        self.buttonMotorsOff = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonMotorsOff.setFont(font)
        self.buttonMotorsOff.setToolTip("")
        self.buttonMotorsOff.setObjectName("buttonMotorsOff")
        self.gridLayout.addWidget(self.buttonMotorsOff, 25, 2, 1, 1)
        self.coloringCombo = QtWidgets.QComboBox(self.layoutWidget)
        self.coloringCombo.setObjectName("coloringCombo")
        self.gridLayout.addWidget(self.coloringCombo, 11, 1, 1, 2)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 12, 0, 1, 3)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 7, 0, 1, 3)
        self.buttonReset = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonReset.setObjectName("buttonReset")
        self.gridLayout.addWidget(self.buttonReset, 28, 0, 1, 3)
        self.videoFrame = QtWidgets.QLabel(self.centralwidget)
        self.videoFrame.setGeometry(QtCore.QRect(20, 10, 1280, 1080))
        self.videoFrame.setMaximumSize(QtCore.QSize(1280, 1280))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.videoFrame.setFont(font)
        self.videoFrame.setObjectName("videoFrame")
        TrackerUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TrackerUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2000, 47))
        self.menubar.setObjectName("menubar")
        TrackerUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TrackerUI)
        self.statusbar.setObjectName("statusbar")
        TrackerUI.setStatusBar(self.statusbar)

        self.retranslateUi(TrackerUI)
        QtCore.QMetaObject.connectSlotsByName(TrackerUI)
        TrackerUI.setTabOrder(self.studyName, self.sourceCombo)
        TrackerUI.setTabOrder(self.sourceCombo, self.buttonConnect)
        TrackerUI.setTabOrder(self.buttonConnect, self.scalingSlider)
        TrackerUI.setTabOrder(self.scalingSlider, self.buttonUp)
        TrackerUI.setTabOrder(self.buttonUp, self.buttonRight)
        TrackerUI.setTabOrder(self.buttonRight, self.buttonDown)
        TrackerUI.setTabOrder(self.buttonDown, self.buttonLeft)
        TrackerUI.setTabOrder(self.buttonLeft, self.buttonMotorsOn)
        TrackerUI.setTabOrder(self.buttonMotorsOn, self.buttonStartRecording)
        TrackerUI.setTabOrder(self.buttonStartRecording, self.buttonStopRecording)
        TrackerUI.setTabOrder(self.buttonStopRecording, self.buttonMotorsOff)
        TrackerUI.setTabOrder(self.buttonMotorsOff, self.loggingCombo)
        TrackerUI.setTabOrder(self.loggingCombo, self.methodCombo)
        TrackerUI.setTabOrder(self.methodCombo, self.buttonRefresh)
        TrackerUI.setTabOrder(self.buttonRefresh, self.coloringCombo)
        TrackerUI.setTabOrder(self.coloringCombo, self.buttonReset)
        TrackerUI.setTabOrder(self.buttonReset, self.boundaryEdit)
        TrackerUI.setTabOrder(self.boundaryEdit, self.buttonRun)

    def retranslateUi(self, TrackerUI):
        _translate = QtCore.QCoreApplication.translate
        TrackerUI.setWindowTitle(_translate("TrackerUI", "NemPy Tracker"))
        self.coloringDesc.setText(_translate("TrackerUI", "Coloring"))
        self.methodDesc.setText(_translate("TrackerUI", "Method"))
        self.buttonRefresh.setText(_translate("TrackerUI", "Refresh"))
        self.loggingDesc.setText(_translate("TrackerUI", "Logging"))
        self.buttonDown.setText(_translate("TrackerUI", "Down"))
        self.motorsDesc.setText(_translate("TrackerUI", "Motorized"))
        self.buttonMotorsOn.setText(_translate("TrackerUI", "On"))
        self.buttonStopRecording.setText(_translate("TrackerUI", "Stop"))
        self.buttonRight.setText(_translate("TrackerUI", "Right"))
        self.buttonLeft.setText(_translate("TrackerUI", "Left"))
        self.buttonUp.setText(_translate("TrackerUI", "Up"))
        self.studyDesc.setText(_translate("TrackerUI", "Study"))
        self.buttonRun.setText(_translate("TrackerUI", "Run"))
        self.sourceDesc.setText(_translate("TrackerUI", "Source"))
        self.boundaryDesc.setText(_translate("TrackerUI", "Boundary"))
        self.buttonConnect.setText(_translate("TrackerUI", "Connect"))
        self.buttonStartRecording.setText(_translate("TrackerUI", "Start"))
        self.fps.setText(_translate("TrackerUI", ""))
        self.scaling.setText(_translate("TrackerUI", "TextLabel"))
        self.fpsDesc.setText(_translate("TrackerUI", "FPS"))
        self.recordingDesc.setText(_translate("TrackerUI", "Recording"))
        self.buttonMotorsOff.setText(_translate("TrackerUI", "Off"))
        self.buttonReset.setText(_translate("TrackerUI", "Reset"))
        self.videoFrame.setText(_translate("TrackerUI", "Select source if video not displayed here on boot up"))

