# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NemPyTracker.ui'
#
# Created: Thu Jul 31 14:13:59 2014
#      by: PyQt5 UI code generator 5.3.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TrackerUI(object):
    def setupUi(self, TrackerUI):
        TrackerUI.setObjectName("TrackerUI")
        TrackerUI.resize(800, 600)
        TrackerUI.setMinimumSize(QtCore.QSize(800, 600))
        TrackerUI.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        TrackerUI.setFont(font)
        self.centralwidget = QtWidgets.QWidget(TrackerUI)
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.videoFrame = QtWidgets.QLabel(self.centralwidget)
        self.videoFrame.setGeometry(QtCore.QRect(10, 40, 640, 480))
        self.videoFrame.setMinimumSize(QtCore.QSize(640, 480))
        self.videoFrame.setMaximumSize(QtCore.QSize(640, 480))
        self.videoFrame.setAlignment(QtCore.Qt.AlignCenter)
        self.videoFrame.setObjectName("videoFrame")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, -1, 487, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.studyControls = QtWidgets.QHBoxLayout()
        self.studyControls.setObjectName("studyControls")
        self.studyDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.studyDesc.setFont(font)
        self.studyDesc.setObjectName("studyDesc")
        self.studyControls.addWidget(self.studyDesc)
        self.studyName = QtWidgets.QLineEdit(self.layoutWidget)
        self.studyName.setMinimumSize(QtCore.QSize(200, 0))
        self.studyName.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.studyName.setFont(font)
        self.studyName.setObjectName("studyName")
        self.studyControls.addWidget(self.studyName)
        self.horizontalLayout.addLayout(self.studyControls)
        self.srcControls = QtWidgets.QHBoxLayout()
        self.srcControls.setObjectName("srcControls")
        self.srcDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.srcDesc.setFont(font)
        self.srcDesc.setObjectName("srcDesc")
        self.srcControls.addWidget(self.srcDesc)
        self.srcCombo = QtWidgets.QComboBox(self.layoutWidget)
        self.srcCombo.setMinimumSize(QtCore.QSize(200, 0))
        self.srcCombo.setMaximumSize(QtCore.QSize(200, 16777215))
        self.srcCombo.setObjectName("srcCombo")
        self.srcControls.addWidget(self.srcCombo)
        self.horizontalLayout.addLayout(self.srcControls)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(670, 30, 121, 481))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonControls = QtWidgets.QVBoxLayout()
        self.buttonControls.setObjectName("buttonControls")
        self.buttonConnect = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonConnect.setFont(font)
        self.buttonConnect.setObjectName("buttonConnect")
        self.buttonControls.addWidget(self.buttonConnect)
        self.buttonRun = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonRun.setFont(font)
        self.buttonRun.setObjectName("buttonRun")
        self.buttonControls.addWidget(self.buttonRun)
        self.buttonRefresh = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonRefresh.setFont(font)
        self.buttonRefresh.setObjectName("buttonRefresh")
        self.buttonControls.addWidget(self.buttonRefresh)
        self.verticalLayout.addLayout(self.buttonControls)
        self.line = QtWidgets.QFrame(self.layoutWidget1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.motoControls = QtWidgets.QVBoxLayout()
        self.motoControls.setObjectName("motoControls")
        self.scaling = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.scaling.setFont(font)
        self.scaling.setAlignment(QtCore.Qt.AlignCenter)
        self.scaling.setObjectName("scaling")
        self.motoControls.addWidget(self.scaling)
        self.scalingSlider = QtWidgets.QSlider(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.scalingSlider.setFont(font)
        self.scalingSlider.setMinimum(1)
        self.scalingSlider.setMaximum(30)
        self.scalingSlider.setOrientation(QtCore.Qt.Horizontal)
        self.scalingSlider.setObjectName("scalingSlider")
        self.motoControls.addWidget(self.scalingSlider)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.buttonUp = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonUp.setFont(font)
        self.buttonUp.setObjectName("buttonUp")
        self.gridLayout.addWidget(self.buttonUp, 0, 1, 1, 1)
        self.buttonLeft = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonLeft.setFont(font)
        self.buttonLeft.setObjectName("buttonLeft")
        self.gridLayout.addWidget(self.buttonLeft, 1, 0, 1, 1)
        self.buttonRight = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonRight.setFont(font)
        self.buttonRight.setObjectName("buttonRight")
        self.gridLayout.addWidget(self.buttonRight, 1, 2, 1, 1)
        self.buttonDown = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonDown.setFont(font)
        self.buttonDown.setObjectName("buttonDown")
        self.gridLayout.addWidget(self.buttonDown, 2, 1, 1, 1)
        self.motoControls.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.motoControls)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.motorizedControls = QtWidgets.QVBoxLayout()
        self.motorizedControls.setObjectName("motorizedControls")
        self.motorsDesc = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.motorsDesc.setFont(font)
        self.motorsDesc.setAlignment(QtCore.Qt.AlignCenter)
        self.motorsDesc.setObjectName("motorsDesc")
        self.motorizedControls.addWidget(self.motorsDesc)
        self.buttonMotorized = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonMotorized.setFont(font)
        self.buttonMotorized.setObjectName("buttonMotorized")
        self.motorizedControls.addWidget(self.buttonMotorized)
        self.verticalLayout.addLayout(self.motorizedControls)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.recControls = QtWidgets.QVBoxLayout()
        self.recControls.setObjectName("recControls")
        self.recordingDesc = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.recordingDesc.setFont(font)
        self.recordingDesc.setAlignment(QtCore.Qt.AlignCenter)
        self.recordingDesc.setObjectName("recordingDesc")
        self.recControls.addWidget(self.recordingDesc)
        self.buttonRec = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonRec.setFont(font)
        self.buttonRec.setObjectName("buttonRec")
        self.recControls.addWidget(self.buttonRec)
        self.verticalLayout.addLayout(self.recControls)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.viewer = QtWidgets.QVBoxLayout()
        self.viewer.setObjectName("viewer")
        self.fpsViewer = QtWidgets.QHBoxLayout()
        self.fpsViewer.setObjectName("fpsViewer")
        self.fpsDesc = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fpsDesc.setFont(font)
        self.fpsDesc.setObjectName("fpsDesc")
        self.fpsViewer.addWidget(self.fpsDesc)
        self.fps = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fps.setFont(font)
        self.fps.setObjectName("fps")
        self.fpsViewer.addWidget(self.fps)
        self.viewer.addLayout(self.fpsViewer)
        self.lcdNumber = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.lcdNumber.setObjectName("lcdNumber")
        self.viewer.addWidget(self.lcdNumber)
        self.verticalLayout.addLayout(self.viewer)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.buttonReset = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonReset.setFont(font)
        self.buttonReset.setObjectName("buttonReset")
        self.verticalLayout.addWidget(self.buttonReset)
        TrackerUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TrackerUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        TrackerUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TrackerUI)
        self.statusbar.setObjectName("statusbar")
        TrackerUI.setStatusBar(self.statusbar)

        self.retranslateUi(TrackerUI)
        QtCore.QMetaObject.connectSlotsByName(TrackerUI)
        TrackerUI.setTabOrder(self.studyName, self.scalingSlider)
        TrackerUI.setTabOrder(self.scalingSlider, self.buttonUp)
        TrackerUI.setTabOrder(self.buttonUp, self.buttonRight)
        TrackerUI.setTabOrder(self.buttonRight, self.buttonDown)
        TrackerUI.setTabOrder(self.buttonDown, self.buttonLeft)
        TrackerUI.setTabOrder(self.buttonLeft, self.buttonRec)
        TrackerUI.setTabOrder(self.buttonRec, self.buttonRefresh)
        TrackerUI.setTabOrder(self.buttonRefresh, self.buttonRun)

    def retranslateUi(self, TrackerUI):
        _translate = QtCore.QCoreApplication.translate
        TrackerUI.setWindowTitle(_translate("TrackerUI", "NemPy Tracker"))
        self.videoFrame.setText(_translate("TrackerUI", "Select source to see video here"))
        self.studyDesc.setText(_translate("TrackerUI", "Study"))
        self.srcDesc.setText(_translate("TrackerUI", "Source"))
        self.buttonConnect.setText(_translate("TrackerUI", "Connect Motors"))
        self.buttonRun.setText(_translate("TrackerUI", "Run Finder"))
        self.buttonRefresh.setText(_translate("TrackerUI", "Refresh Ref"))
        self.scaling.setText(_translate("TrackerUI", "TextLabel"))
        self.buttonUp.setText(_translate("TrackerUI", "Up"))
        self.buttonLeft.setText(_translate("TrackerUI", "Left"))
        self.buttonRight.setText(_translate("TrackerUI", "Right"))
        self.buttonDown.setText(_translate("TrackerUI", "Down"))
        self.motorsDesc.setText(_translate("TrackerUI", "Motorized"))
        self.buttonMotorized.setText(_translate("TrackerUI", "On"))
        self.recordingDesc.setText(_translate("TrackerUI", "Recording"))
        self.buttonRec.setText(_translate("TrackerUI", "Start"))
        self.fpsDesc.setText(_translate("TrackerUI", "FPS"))
        self.fps.setText(_translate("TrackerUI", "TextLabel"))
        self.buttonReset.setText(_translate("TrackerUI", "Reset"))

